### ISSUE TITLE
Error of parsing error constraints in tspa() function

### ISSUE THREAD

**Issue by Gengrui-Zhang** [Gengrui-Zhang/R2spa#10]
@winniewytse @YI-XIAO-LI 
It seems that there is an error in parsing error_constraint[x] because of the variable names in the dataset. 
In the example, the dataset is a set of factor scores so the variable names should have prefixes of "fs_".
We can talk about this in the next meeting. Thanks!

`for (x in 1:len) {
    latent_var[x] <- paste0(var[x], ' =~ 1 * ', fs[x], '\n')
    error_constraint[x] <- paste0(fs[x], ' ~~ ev', x, ' * ', fs[x], '\n') **#probably we need to add fs_ ?**
    latent_variance[x] <- paste0(var[x], ' ~~ v', x, ' * ', var[x], '\n')
    reliability_constraint[x] <- paste0('v', x, ' == ', toString(reliability[x]), ' / ', toString(1 - reliability[x]), ' * ev', x, '\n')
  }
`

**Comment by winniewytse** [comment]
Hey @Gengrui-Zhang, we decided to build `tspa()` such that it constrains the standard errors instead of reliabilities. I updated the examples in `tspa.R`. Please feel free to check out those. @YI-XIAO-LI is going to make changes on the `tspa()` so feel free to come back and test out the function later. Thanks!

Winnie
